name: Vercel Preview Deployment Frontend
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}
on:
  push:
    branches-ignore:
      - master
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: echo "DEPLOY_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_ENV
      - name: Send Deployment Notification to Discord
        if: success()
        run: |
          DEPLOYMENT_URL=${{ env.DEPLOY_URL }}
          COMMIT_HASH=${{ github.sha }}
          COMMIT_USER=${{ github.actor }}
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          BRANCH_NAME=${{ github.ref_name }}
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"ğŸš€ **New PREVIEW Frontend deployment successful!**\n\nğŸ”— URL: $DEPLOYMENT_URL\n\nğŸ“œ Commit: [$COMMIT_HASH](https://github.com/${{ github.repository }}/commit/$COMMIT_HASH)\nğŸ‘¤ $COMMIT_USER\nğŸ“ $COMMIT_MESSAGE\nğŸŒ¿ $BRANCH_NAME\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
