name: Vercel Production Deployment Backend
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_BACKEND }}
  WEB_URL: 'https://chillmate-backend-gamma.vercel.app'
on:
  push:
    branches:
      - master
    paths:
      - application/backend/**
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: echo "DEPLOY_URL=$(vercel deploy --prebuilt --archive=tgz --prod --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_ENV
      - name: Send Deployment Notification to Discord
        if: ${{ env.DEPLOY_URL != '' }}
        run: |
          DEPLOYMENT_URL=${{ env.DEPLOY_URL }}
          COMMIT_HASH=${{ github.sha }}
          COMMIT_HASH_SHORT=$(git rev-parse --short HEAD)
          COMMIT_USER=${{ github.actor }}
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          BRANCH_NAME=${{ github.ref_name }}
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"\n\nüöÄ **New Production _Backend_ deployment successful!**\n\nüîó Deployment URL: $DEPLOYMENT_URL (${{ env.WEB_URL }}) \n\nüìú Commit: [$COMMIT_HASH_SHORT](https://github.com/${{ github.repository }}/commit/$COMMIT_HASH)\nüìù $COMMIT_USER - $COMMIT_MESSAGE\n\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
